-- MySQL Script generated by MySQL Workbench
-- 30.03.2016 (ср) 11,26,21 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Project_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project_1` DEFAULT CHARACTER SET utf8 ;
USE `Project_1` ;

-- -----------------------------------------------------
-- Table `Project_1`.`interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`interest` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`interest` (
  `interest_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `interestcol` VARCHAR(45) NULL,
  PRIMARY KEY (`interest_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Project_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`users` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_fname` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_lname` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_mail` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_pass` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `user_story` VARCHAR(255) NULL,
  `user_about` VARCHAR(450) NULL,
  PRIMARY KEY (`user_id`, `user_mail`, `user_pass`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `user_mail_UNIQUE` ON `Project_1`.`users` (`user_mail` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `Project_1`.`users` (`username` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`messege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`messege` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`messege` (
  `messege_id` INT UNSIGNED NULL AUTO_INCREMENT,
  `message_text` VARCHAR(255) NOT NULL,
  `message_sender` INT UNSIGNED NOT NULL,
  `message_recipient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`messege_id`))
ENGINE = MyISAM;

CREATE INDEX `fk_messege_users1_idx` ON `Project_1`.`messege` (`message_sender` ASC);

CREATE INDEX `fk_messege_users2_idx` ON `Project_1`.`messege` (`message_recipient` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`interest_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`interest_tree` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`interest_tree` (
  `parrent_id` SMALLINT UNSIGNED NOT NULL,
  `child_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`parrent_id`),
  CONSTRAINT `fk_interest_tree_interest1`
    FOREIGN KEY (`child_id`)
    REFERENCES `Project_1`.`interest` (`interest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_child_UNIQUE` ON `Project_1`.`interest_tree` (`child_id` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`users_has_interest_tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`users_has_interest_tree` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`users_has_interest_tree` (
  `users_user_id` INT UNSIGNED NOT NULL,
  `interest_tree_id_parrent` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_user_id`, `interest_tree_id_parrent`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_users_has_interest_tree_interest_tree1_idx` ON `Project_1`.`users_has_interest_tree` (`interest_tree_id_parrent` ASC);

CREATE INDEX `fk_users_has_interest_tree_users1_idx` ON `Project_1`.`users_has_interest_tree` (`users_user_id` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`users_has_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`users_has_friends` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`users_has_friends` (
  `users_user_id` INT UNSIGNED NOT NULL,
  `users_friend_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_user_id`, `users_friend_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_users_has_users_users2_idx` ON `Project_1`.`users_has_friends` (`users_friend_id` ASC);

CREATE INDEX `fk_users_has_users_users1_idx` ON `Project_1`.`users_has_friends` (`users_user_id` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`picture` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`picture` (
  `picture_id` INT UNSIGNED NOT NULL,
  `picture_url` VARCHAR(255) NOT NULL,
  `users_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`picture_id`, `users_user_id`),
  CONSTRAINT `fk_table1_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `Project_1`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `url_picture_UNIQUE` ON `Project_1`.`picture` (`picture_url` ASC);

CREATE INDEX `fk_table1_users1_idx` ON `Project_1`.`picture` (`users_user_id` ASC);


-- -----------------------------------------------------
-- Table `Project_1`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`city` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`city` (
  `city_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(150) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project_1`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project_1`.`adress` ;

CREATE TABLE IF NOT EXISTS `Project_1`.`adress` (
  `adress_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `str_name` VARCHAR(255) NULL,
  `str_number` VARCHAR(5) NULL,
  `city_city_id` INT UNSIGNED NOT NULL,
  `users_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`adress_id`, `city_city_id`),
  CONSTRAINT `fk_adress_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `Project_1`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adress_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `Project_1`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_adress_city1_idx` ON `Project_1`.`adress` (`city_city_id` ASC);

CREATE INDEX `fk_adress_users1_idx` ON `Project_1`.`adress` (`users_user_id` ASC);

CREATE UNIQUE INDEX `users_user_id_UNIQUE` ON `Project_1`.`adress` (`users_user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
